# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from refnd import kernels
import typing
__all__ = [
    "CsrGraph",
    "EdgeStore",
    "EdgeStoreIter",
    "HNSWConfig",
    "HNSWIndex",
    "HNSWState",
    "LeidenObjective",
    "connected_components",
    "exact_edges",
    "exact_nearest_neighbors",
    "find_communities",
    "partition",
]

@typing.final
class CsrGraph:
    r"""
    Compressed Sparse Row graph built from an ``EdgeStore``. A CSR graph is compact, and highly
    efficient for traversal, exploiting cache structure and maximizing cache hits. However, it is
    immutable, so adding a new node or edge require building the full graph again.
    
    ``CsrGraph`` is an immutable adjacency structure. Because of its property of being very
    efficient for traversal, it is used by graph algorithms such as ``partition`` and
    ``connected_components``.
    
    Properties:
        - ``n``: Number of nodes.
        - ``m``: Sum of all edge weights (or total edge count when ``use_weight=False``).
    
    Example::
    
        from refnd.core import EdgeStore, CsrGraph
    
        store = EdgeStore(4, [(0,1,0.9),(1,2,0.8),(2,3,0.6)])
        g = CsrGraph(store, use_weight=True)
        print(g.n)               # 4
        print(g.neighbors(1))    # [(0, 0.9), (2, 0.8)]
        print(g.strength(1))     # 1.7
    """
    @property
    def n(self) -> builtins.int:
        r"""
        Number of nodes
        """
    @property
    def m(self) -> builtins.float:
        r"""
        Total weight (each edge counted once)
        """
    def __new__(cls, edges: EdgeStore, use_weight: builtins.bool = True, is_weight_distance: builtins.bool = True) -> CsrGraph:
        r"""
        Build a CsrGraph from an EdgeStore.
        
        Args:
            edges: The edge store to build the graph from.
            use_weight: If ``True``, edge weights are used for graph operations.
            is_weight_distance: If ``True`` (default), raw weights are treated as
                                distances and converted to similarities internally
                                (``similarity = 1 - distance``). Set to ``False``
                                when weights are already similarities.
        """
    def neighbors(self, v: builtins.int) -> builtins.list[tuple[builtins.int, builtins.float]]:
        r"""
        Return the neighbors of node ``v`` as a list of ``(node_id, weight)`` pairs.
        
        Args:
            v: Zero-based node index.
        """
    def strength(self, v: builtins.int) -> builtins.float:
        r"""
        Return the strength (weighted degree) of node ``v``.
        
        When the graph is unweighted this equals the degree (number of neighbors).
        
        Args:
            v: Zero-based node index.
        """

@typing.final
class EdgeStore:
    r"""
    A compact, flat list of weighted directed edges between integer node IDs.
    
    ``EdgeStore`` is the central data carrier in refnd: it is produced by
    ``exact_edges`` and ``HNSWState.edges``, consumed by ``CsrGraph``, and can be
    persisted to disk for later reuse.
    
    Each edge is a triple ``(src, dst, weight)`` where ``src`` and ``dst`` are
    zero-based node indices in ``[0, node_count)`` and ``weight`` is a ``float32``
    similarity score (higher = more similar, unless the graph is built with
    ``is_weight_distance=True``, in such case it's a real distance ``[0, ∞)`` that will be converted
    to a similarity score).
    
    Example::
    
        from refnd.core import EdgeStore
    
        store = EdgeStore(node_count=3, edges=[(0, 1, 0.9), (1, 2, 0.7)])
        print(len(store))     # 2
        print(store[0])       # (0, 1, 0.9)
        for src, dst, w in store:
            print(src, dst, w)
    """
    def __new__(cls, node_count: builtins.int, edges: typing.Sequence[tuple[builtins.int, builtins.int, builtins.float]]) -> EdgeStore:
        r"""
        Create a new EdgeStore.
        
        Args:
            node_count: Total number of nodes in the graph (must be ≥ the largest node ID + 1).
            edges: List of ``(src, dst, weight)`` triples. Weights are ``float32`` similarity scores.
        """
    def edges(self) -> builtins.list[tuple[builtins.int, builtins.int, builtins.float]]:
        r"""
        Return all edges as a list of ``(src, dst, weight)`` triples.
        """
    def node_count(self) -> builtins.int:
        r"""
        Return the total number of nodes this store was created with.
        """
    def graph(self, weighted: builtins.bool = True, is_weight_distance: builtins.bool = True) -> CsrGraph:
        r"""
        Build a ``CsrGraph`` from this edge store.
        
        Args:
            use_weight: If ``True``, edge weights are used for graph operations (e.g. strength).
                        If ``False``, all edges are treated as unweighted (weight = 1.0).
            is_weight_distance: If ``True``, edges weights are normalized to have a maximal bound of
                                1 using this formula: ``1.0 / (1.0 + w)`` since the Leiden algorithm works on
                                similarity graphs.
        
        Returns:
            A ``CsrGraph`` backed by this edge list.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Serialize this EdgeStore to disk. It supports two file formats: ``text`` with
        ``.edgelist`` extension or ``binary`` with ``.edgestr`` extension. Binary is usually 2x
        more space efficient at the cost of not being human-readable.
        
        Args:
            path: Destination file path.
        
        Raises:
            IOError: On any I/O failure.
        Example::
        
            from refnd.core import EdgeStore
        
            store = EdgeStore(node_count=3, edges=[(0, 1, 0.9), (1, 2, 0.7)])
            store.save("my/path/myedges.edgelist") # Text format
            store.save("my/path/myedges.edgestr")  # Bin format
        """
    @staticmethod
    def load(path: builtins.str) -> EdgeStore:
        r"""
        Load an EdgeStore that was previously saved with ``EdgeStore.save``. It infers the format
        from the extension of the path, ``.edgelist`` or ``.edgestr``.
        
        Args:
            path: Path to the file produced by ``save``.
        
        Returns:
            The deserialized ``EdgeStore``.
        
        Raises:
            IOError: If the file cannot be read or the format is invalid.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> tuple[builtins.int, builtins.int, builtins.float]: ...
    def __iter__(self) -> EdgeStoreIter: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class EdgeStoreIter:
    ...

@typing.final
class HNSWConfig:
    r"""
    Configuration for the HNSW approximate nearest-neighbour index.
    
    All parameters have sensible defaults; in most cases you only need to ``ef_construction``, and
    ``proximity_threshold``.
    
    **Parameters:**
    
    - ``proximity_threshold`` *(float)* — Distance threshold under which a connection is established in the proximity graph.
    - ``ef_construction`` *(int)* — Candidate list size during build. Default ``64``.
    - ``m`` *(int)* — Bidirectional links per node at layers > 0.
      Higher = better recall, more memory, slower build. Typical: 8–64.
    - ``m_max`` *(int)* — Maximum connections per node at layers > 0. Usually equal to ``m``.
    - ``m_max0`` *(int)* — Maximum connections at layer 0. Usually ``2 * m``.
    - ``m_l`` *(float)* — Level generation factor. Usually ``0.36 ≈ 1 / ln(m)``.
    - ``ef_init`` *(int)* — Candidate list size during initial-layer insertion. Almost always 1 for
      a greedy search.
    - ``extend_candidates`` *(bool)* — Use neighbors of neighbors as candidates, making search more exhaustive.
    - ``keep_pruned_connections`` *(bool)* — Retain discarded candidates to fill up to ``m`` connections when not enough connections are found.
    - ``cache_capacity`` *(int)* — Maximum cached kernel scores. Increasing it increase the memory
      footprint, but also cache hits, which can improve runtime performances for computationally expensive kernels.
    - ``cache_shards`` *(int)* — Number of cache shards (reduces lock contention).
    - ``n_threads`` *(int)* — Threads used during build. ``0`` = all available cores.
    - ``shuffle`` *(bool)* — Shuffle insertion order before building. Can create a less biased
      graph, but reduces cache hits, which increases runtime.
    - ``use_heuristic`` *(bool)* — Use the heuristic neighbour-selection from the paper (recommended).
    - ``strict_ef`` *(bool)* — If ``True``, enforces the result set size to exactly ``ef`` during search. Empirically, setting this to ``False`` can improve runtime performance, as it allows halving ``ef_construction`` without sacrificing accuracy.
    - ``threshold_based_neighbourhood`` *(bool)* — Select a minimum of ``m`` neighbors like the classic algorithm, but doesn't bound the neighbourhood size as all candidates that are closer than the threshold are kept.
    """
    @property
    def m(self) -> builtins.int: ...
    @property
    def m_max(self) -> builtins.int: ...
    @property
    def m_max0(self) -> builtins.int: ...
    @property
    def m_l(self) -> builtins.float: ...
    @property
    def ef_init(self) -> builtins.int: ...
    @property
    def ef_construction(self) -> builtins.int: ...
    @property
    def extend_candidates(self) -> builtins.bool: ...
    @property
    def keep_pruned_connections(self) -> builtins.bool: ...
    @property
    def cache_capacity(self) -> builtins.int: ...
    @property
    def cache_shards(self) -> builtins.int: ...
    @property
    def proximity_threshold(self) -> builtins.float: ...
    @property
    def n_threads(self) -> builtins.int: ...
    @property
    def shuffle(self) -> builtins.bool: ...
    @property
    def use_heuristic(self) -> builtins.bool: ...
    @property
    def strict_ef(self) -> builtins.bool: ...
    @property
    def threshold_based_neighbourhood(self) -> builtins.bool: ...
    def __new__(cls, proximity_threshold: builtins.float = 0.5, ef_construction: builtins.int = 64, m: builtins.int = 16, m_max: builtins.int = 16, m_max0: builtins.int = 32, m_l: builtins.float = 0.36, ef_init: builtins.int = 1, extend_candidates: builtins.bool = False, keep_pruned_connections: builtins.bool = True, cache_capacity: builtins.int = 2000000, cache_shards: builtins.int = 64, n_threads: builtins.int = 0, shuffle: builtins.bool = False, use_heuristic: builtins.bool = True, strict_ef: builtins.bool = False, threshold_based_neighbourhood: builtins.bool = False) -> HNSWConfig:
        r"""
        Create an HNSWConfig. See class docstring for parameter descriptions.
        """
    def dict(self) -> dict:
        r"""
        Return the configuration as a plain Python dict.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class HNSWIndex:
    r"""
    Read-only snapshot of the HNSW graph structure after a build.
    
    Obtained via ``HNSWState.index``. Primarily useful for inspection,
    serialisation, and debugging; normal users interact with ``HNSWState``
    instead.
    
    Properties:
        dataset_size (int): Number of items indexed.
        layers (list): Nested multi-layer adjacency list ``layers[layer][node] = [neighbor_ids]``.
        entry_point (tuple | None): ``(layer, node_id)`` of the global entry point, or ``None`` if empty.
        max_layers (int): Number of layers in the hierarchy.
        proximity_edges (list): List of ``((src, dst), score)`` for proximity-threshold edges.
        config (HNSWConfig): The config used to build this index.
    """
    @property
    def dataset_size(self) -> builtins.int: ...
    @property
    def layers(self) -> builtins.list[builtins.list[builtins.list[builtins.int]]]: ...
    @property
    def entry_point(self) -> typing.Optional[tuple[builtins.int, builtins.int]]: ...
    @property
    def max_layers(self) -> builtins.int: ...
    @property
    def proximity_edges(self) -> builtins.list[tuple[tuple[builtins.int, builtins.int], builtins.float]]: ...
    @property
    def config(self) -> HNSWConfig: ...
    def save(self, path: builtins.str) -> None:
        r"""
        Save the object to a binary representation (e.g. *.hnsw* file).
        
        Args:
            path: Destination file path (recommended with a .hnsw extension)
        
        Raises:
            RuntimeError: On serialisation or I/O failure.
        """
    @staticmethod
    def load(path: builtins.str) -> HNSWIndex:
        r"""
        Load an index previously saved with ``HNSWIndex.save``.
        
        Args:
            path: Path to the saved file.
        
        Returns:
            The deserialised ``HNSWIndex``.
        
        Raises:
            RuntimeError: If the file cannot be read or the format is invalid.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class HNSWState:
    r"""
    Stateful Hierarchical Navigable Small World (HNSW) approximate nearest-neighbour index. This
    class is used to build and search in the index, whereas ``HNSWIndex`` is a read-only *internal*
    representation of the index used for saving / loading / structure exploration.
    
    ``HNSWState`` wraps the dataset and the graph index together. The typical
    workflow is:
    
    1. Construct with the data and a ``KernelVariant``.
    2. Call ``build()`` to insert all items and form the graph.
    3. Call ``search()`` to query, or ``edges()`` to extract the proximity graph
       for downstream clustering / splitting.
    
    HNSW parameters (``proximity_threshold``, ``ef_construction``, …) are the same as ``HNSWConfig``
    and can be passed directly to the constructor as keyword arguments.
    
    Args:
        variant: Kernel to use (e.g.  ``KernelVariant.ProteinGlobal``, ``KernelVariant.ProteinLocal``, ``KernelVariant.TanimotoBit``, *etc*).
        data: The dataset — a list of items matching the kernel type (e.g. ``list[str]`` or ``list[np.ndarray]``).
        proximity_threshold, ef_construction, m, m_max, m_max0, m_l, ef_init, extend_candidates,
            keep_pruned_connections, cache_capacity, cache_shards,
            n_threads, shuffle, use_heuristic, strict_ef,
            threshold_based_neighbourhood: See ``HNSWConfig`` for descriptions.
    
    Properties:
        config (HNSWConfig): The config in use.
        index (HNSWIndex): A snapshot of the current graph structure.
    
    Example::
    
        from refnd import HNSWState, KernelVariant
    
        seqs = ["MKTAYIAK", "MKTAYIAKQR", "ACDEFGHIKLM", "MKTAYIAKQRQIS"]
        state = HNSWState(KernelVariant.ProteinGlobal, seqs, proximity_threshold=0.3, ef_construction=64)
        state.build()
        results = state.search(["MKTAYIAK"], k=2)
        # results[0] -> [(0, 1.0), (1, 0.88)]
    
        store = state.edges()        # EdgeStore for graph-based splitting
        state.save("index.hnsw")
        state2 = HNSWState.load(KernelVariant.ProteinGlobal, "index.hnsw", seqs)
    """
    @property
    def is_built(self) -> builtins.bool:
        r"""
        Whether ``build`` has been called on this index.
        """
    @property
    def config(self) -> HNSWConfig:
        r"""
        Config used to initiate this object.
        """
    @property
    def index(self) -> HNSWIndex:
        r"""
        HNSWIndex snapshot.
        """
    def __new__(cls, variant: kernels.KernelVariant, data: typing.Any, *args: typing.Any, proximity_threshold: builtins.float = 0.5, ef_construction: builtins.int = 64, m: builtins.int = 16, m_max: builtins.int = 16, m_max0: builtins.int = 32, m_l: builtins.float = 0.36, ef_init: builtins.int = 1, extend_candidates: builtins.bool = False, keep_pruned_connections: builtins.bool = True, cache_capacity: builtins.int = 2000000, cache_shards: builtins.int = 64, n_threads: builtins.int = 0, shuffle: builtins.bool = False, use_heuristic: builtins.bool = True, strict_ef: builtins.bool = False, threshold_based_neighbourhood: builtins.bool = False, **kwargs: typing.Any) -> HNSWState: ...
    def build(self, progress: builtins.bool = True) -> None:
        r"""
        Build the HNSW index by inserting all data items.
        
        Must be called before ``search`` or ``edges``. Calling ``build`` a second
        time raises a ``RuntimeError``; construct a new ``HNSWState`` instead.
        
        Args:
            progress: Display a progress bar. Defaults to ``True``.
        
        Raises:
            RuntimeError: If the index has already been built.
        """
    def search(self, queries: typing.Any, k: builtins.int = 1, ef: builtins.int = 64, threads: builtins.int = 0, progress: builtins.bool = True) -> builtins.list[builtins.list[tuple[builtins.int, builtins.float]]]:
        r"""
        Search the index for approximate nearest neighbours.
        
        For each query item, returns the ``k`` most similar items in the dataset,
        sorted by descending similarity. The quality of the approximation is
        controlled by ``ef``: larger values explore more candidates and improve
        recall at the cost of speed.
        
        Args:
            queries: List of query items (same type as the indexed data).
            k: Number of nearest neighbours to return per query. Defaults to ``1``.
            ef: Size of the dynamic candidate list during search. Must be ≥ ``k``.
                Defaults to ``64``.
            threads: Number of parallel threads. ``0`` = all available cores.
            progress: Display a progress bar. Defaults to ``True``.
        
        Returns:
            A list of length ``len(queries)``. Each element is a sorted list of
            up to ``k`` tuples ``(dataset_index, similarity_score)``.
        
        Raises:
            RuntimeError: If ``build`` has not been called yet.
        """
    def edges(self) -> EdgeStore:
        r"""
        Extract the proximity graph as an ``EdgeStore``.
        
        Returns all edges found during ``build``. All distance measurements below the
        ``proximity_threshold``.
        
        Returns:
            An ``EdgeStore`` with ``node_count = dataset_size``.
        """
    def get_layer(self, layer_idx: builtins.int) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Return the adjacency lists for a specific HNSW layer.
        
        Args:
            layer_idx: Zero-based layer index (0 = base layer with most nodes).
        
        Returns:
            A list of length ``dataset_size`` where element ``i`` is the list of
            neighbour IDs of node ``i`` at this layer. Node IDs are their index in the original dataset.
        
        Raises:
            IndexError: If ``layer_idx`` is out of range.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Serialize the full state (index + config) to a binary file.
        
        The saved file can be loaded back with ``HNSWState.load``. The original
        data must be provided again at load time (it is not embedded in the file).
        
        Args:
            path: Destination file path.
        
        Raises:
            RuntimeError: On serialisation or I/O failure.
        """
    @staticmethod
    def load(variant: kernels.KernelVariant, path: builtins.str, data: typing.Any, *args: typing.Any, **kwargs: typing.Any) -> HNSWState:
        r"""
        Load an HNSWState form a binary file saved with ``HNSWState.save``.
        
        Args:
            variant: Must match the kernel used during the original build.
            path: Path to the saved file.
            data: The original dataset (required to re-attach the kernel).
        
        Returns:
            The restored ``HNSWState``, ready to call ``search`` or ``edges`` if the index was built.
        
        Raises:
            RuntimeError: If the file cannot be read or the format is invalid.
        """

@typing.final
class LeidenObjective(enum.Enum):
    r"""
    Objective function used by the Leiden community-detection algorithm.
    
    - ``Modularity`` — Maximise Newman-Girvan modularity. Good default for most graphs.
    - ``CPM`` — Constant Potts Model. Finds communities of a fixed internal density.
    """
    Modularity = ...
    CPM = ...

def connected_components(graph: CsrGraph) -> builtins.list[builtins.int]:
    r"""
    Finds the connected components of a graph.
    
    Runs a standard BFS/union-find over the graph and assigns each node to
    its component.
    
    Args:
        graph: The graph to find components.
    
    Returns:
        A list of length ``graph.n`` where element ``i`` is the component ID of
        node ``i``. IDs are arbitrary non-negative integers.
    
    Example::
    
        from refnd.core import EdgeStore, connected_components
    
        store = EdgeStore(6, [(0,1,0.9),(1,2,0.8),(3,4,0.7),(4,5,0.6)])
        g = store.graph()
        clusters = connected_components(g) # [0, 0, 0, 1, 1, 1]
    """

def exact_edges(variant: kernels.KernelVariant, data: typing.Any, proximity_threshold: builtins.float = 0.5, threads: builtins.int = 0, progress: builtins.bool = True, *args: typing.Any, **kwargs: typing.Any) -> EdgeStore:
    r"""
    Compute all pairs of data points whose similarity exceeds a threshold (exact, brute-force).
    
    Evaluates every unordered pair ``(i, j)`` with ``i < j`` and records an edge
    when ``kernel(data[i], data[j]) <= proximity_threshold``. This is O(n²) in the number
    of data points; prefer the approximate``HNSWState`` for large datasets.
    
    Extra positional and keyword arguments are forwarded to the kernel constructor.
    
    Args:
        variant: Which kernel to use (``KernelVariant.ProteinGlobal`` or
                 ``KernelVariant.ProteinLocal``).
        data: Sequence of data items (e.g. ``list[str]`` for protein sequences).
        proximity_threshold: Maximum distance for an edge to be recorded.
        threads: Number of parallel threads. ``0`` uses all available cores.
        progress: Show a progress bar. Defaults to ``True``.
    
    Returns:
        An ``EdgeStore`` containing all edges whose distance ≤ ``proximity_threshold``.
    
    Example::
    
        from refnd import KernelVariant, exact_edges
    
        seqs = ["MKTAYIAK", "MKTAYIAKQR", "ACDEFGHIKLM"]
        store = exact_edges(KernelVariant.ProteinGlobal, seqs, proximity_threshold=0.5)
        print(len(store))   # number of similar pairs
    """

def exact_nearest_neighbors(variant: kernels.KernelVariant, queries: typing.Any, references: typing.Any, k: builtins.int, threads: builtins.int = 0, progress: builtins.bool = True, *args: typing.Any, **kwargs: typing.Any) -> builtins.list[builtins.list[tuple[builtins.int, builtins.float]]]:
    r"""
    Find the k nearest neighbors of each query in a reference set (exact, brute-force).
    
    For every query item, scores it against every reference item using the
    chosen kernel and returns the top-k references sorted by ascending
    distance. Complexity is O(n_queries × n_references); prefer
    ``HNSWState.search`` for approximate nearest neighbors with large datasets.
    
    Extra positional and keyword arguments are forwarded to the kernel constructor.
    
    Args:
        variant: Which kernel to use (e.g. ``KernelVariant.ProteinGlobal`` or
                 ``KernelVariant.TanimotoBit``).
        queries: Sequence of query items.
        references: Sequence of reference items to search over. List of items of the same type of the selected kernel variant.
        k: Number of nearest neighbors to return per query. List of items of the same type of the selected kernel variant.
        threads: Number of parallel threads. ``0`` uses all available cores.
        progress: Show a progress bar. Defaults to ``True``.
    
    Returns:
        A list of length ``len(queries)``. Each element is a list of up to ``k``
        tuples ``(reference_index, similarity_score)`` sorted by ascending distance.
    
    Example::
    
        from refnd import KernelVariant, exact_nearest_neighbors
    
        queries = ["MKTAYIAK"]
        refs    = ["MKTAYIAKQR", "ACDEFGHIKLM", "MKTAYIAKQRQ"]
        results = exact_nearest_neighbors(
            KernelVariant.ProteinGlobal, queries, refs, k=2
        )
        # results[0] -> [(0, 0.20), (2, 0.27)]
    """

def find_communities(graph: CsrGraph, gamma: builtins.float = 1.0, beta: builtins.float = 0.01, n_iterations: builtins.int = 2, objective: LeidenObjective = LeidenObjective.Modularity) -> builtins.list[builtins.int]:
    r"""
    Detect communities in a graph with the Leiden algorithm.
    
    The Leiden algorithm is an improvement over Louvain that guarantees
    well-connected communities. Use the returned cluster labels with
    ``partition`` to produce train/test splits that consider community boundaries.
    
    Args:
        graph: The graph to partition into communities.
        gamma: Resolution parameter. Higher values produce more, smaller communities.
               For ``Modularity``, typical range is 0.5–2.0; default ``1.0``.
               For ``CPM``, it represents the minimum internal edge density.
        beta: Randomness parameter controlling the refinement phase.
              Smaller values yield more deterministic results. Default ``0.01``.
        n_iterations: Number of optimisation passes. More iterations improve
                      quality at the cost of runtime.
        objective: ``LeidenObjective.Modularity`` (default) or ``LeidenObjective.CPM``.
    
    Returns:
        A list of length ``graph.n`` where element ``i`` is the cluster ID of node ``i``.
        Cluster IDs are arbitrary non-negative integers.
    
    Example::
    
        from refnd.core import CsrGraph, EdgeStore, find_communities, LeidenObjective
    
        store = EdgeStore(4, [(0,1,0.9),(1,2,0.8),(2,3,0.6)])
        g = CsrGraph(store, use_weight=True, is_weight_distance=False)
        clusters = find_communities(g, gamma=1.0, n_iterations=20) # e.g. [0, 1, 2, 3]
    """

def partition(clusters: typing.Sequence[builtins.int], graph: CsrGraph, test_ratio: builtins.float = 0.2, seed: typing.Optional[builtins.int] = None, post_filtering: builtins.bool = False) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int]]:
    r"""
    Split a clustered dataset into train and test index sets along clusters
    
    Clusters are kept intact — no cluster is split across train and test.
    The function greedily and randomly assigns whole clusters to the test set until the test size
    is larger than ``test_ratio``, then assigns the rest to train.
    
    This is the key function for leakage-free dataset splitting: run
    ``find_communities``, ``connected_components``, or your own clustering, then call ``partition``
    to obtain indices you can use to slice your data arrays.
    
    Args:
        clusters: A list of cluster IDs, one per data point (as returned by
                  ``find_communities`` or ``connected_components``). Length must
                  equal the number of nodes in ``graph``.
        graph: The graph used to derive community structure. Its node count
               must match ``len(clusters)``.
        test_ratio: Target fraction of data points to place in the test set.
                    The actual fraction may differ slightly because clusters
                    are indivisible. Defaults to ``0.2``.
        seed: Optional integer seed for reproducible cluster shuffling.
              Pass ``None`` for a random assignment.
        post_filtering: If ``True``, remove train nodes that share an edge with
                        any test node (stricter leakage prevention at the
                        cost of a smaller train set). Use only when clusters are found from
                        communities (``find_communities``). It won't have any effect when used with
                        ``connected_components`` as this prevents inter-cluster connections.
    
    Returns:
        A tuple ``(train_indices, test_indices)`` of zero-based data-point indices.
    
    Raises:
        ValueError: If ``clusters`` length does not match ``graph.n``, or if
                    ``test_ratio`` is not in ``(0, 1)``.
    
    Example::
    
        from refnd.core import (
            EdgeStore, CsrGraph, find_communities, partition
        )
    
        store = EdgeStore(6, [(0,1,0.9),(1,2,0.8),(3,4,0.7),(4,5,0.6)])
        g = CsrGraph(store, use_weight=True, is_weight_distance=False)
        clusters = find_communities(g) # or connected_components(g)
        train_idx, test_idx = partition(clusters, g, test_ratio=0.3, seed=42)
    """

