[project]
name = "ablation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "datasets>=5.0.0",
    "esm>=3.2.3",
    "huggingface-hub[hf-xet]",
    "qmap-benchmark>=0.1.1",
    "rdkit>=2026.3.3",
    "refnd",
    "rich>=15.0.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "transformers",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }
refnd = { path = "../py" }
