# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
from rdkit.DataStructs.cDataStructs import ExplicitBitVect, UIntSparseIntVect
__all__ = [
    "BitFingerprint",
    "RealFingerprint",
    "largest_cluster",
    "read_fasta",
]

@typing.final
class BitFingerprint:
    r"""
    Dense binary fingerprint backed by a dense bitset.
    
    Each bit represents the presence or absence of a structural feature.
    The primary source is an RDKit ``ExplicitBitVect`` (from ``GetFingerprint``),
    but plain Python lists and numpy arrays are also accepted.
    
    ``count`` caches the popcount so Tanimoto computation avoids re-counting.
    
    Example::
    
        from rdkit.Chem import rdFingerprintGenerator, MolFromSmiles
        from refnd.utils import BitFingerprint
    
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(fpSize=1024, radius=2)
        mol = MolFromSmiles("c1ccccc1")
        fp = BitFingerprint(mfpgen.GetFingerprint(mol))
        print(fp.count(), len(fp))   # set bits, total bits
    """
    def __new__(cls, fp: ExplicitBitVect) -> BitFingerprint:
        r"""
        Construct from an RDKit ``ExplicitBitVect`` (e.g. from ``GetFingerprint``).
        
        Raises ``TypeError`` if given a ``SparseBitVect`` from ``GetSparseFingerprint``.
        That type uses a hash-based sparse representation incompatible with the dense
        bit layout required here. Use ``GetFingerprint`` to get an ``ExplicitBitVect``.
        """
    @staticmethod
    def from_list(values: typing.Sequence[builtins.bool]) -> BitFingerprint:
        r"""
        Construct from a list of booleans (or 0/1 ints).
        """
    @staticmethod
    def from_np(arr: numpy.typing.NDArray[numpy.bool_]) -> BitFingerprint:
        r"""
        Construct from a numpy boolean or uint8 array.
        """
    def to_rdkit(self) -> ExplicitBitVect:
        r"""
        Export as an RDKit ``ExplicitBitVect``.
        """
    def to_list(self) -> builtins.list[builtins.bool]:
        r"""
        Export as a list of booleans.
        """
    def to_np(self) -> numpy.typing.NDArray[numpy.bool_]:
        r"""
        Export as a numpy bool array.
        """
    def __len__(self) -> builtins.int: ...
    def count(self) -> builtins.int:
        r"""
        Number of on bits (popcount).
        """

@typing.final
class RealFingerprint:
    r"""
    Dense real-valued fingerprint backed by a ``Vec<f32>``.
    
    Each element represents a feature count or continuous value. The primary
    source is an RDKit ``UIntSparseIntVect`` (from ``GetCountFingerprint``),
    but plain Python lists and numpy arrays are also accepted.
    
    ``norm_sq`` caches ``||x||²`` so Tanimoto computation avoids recomputing it.
    
    Example::
    
        from rdkit.Chem import rdFingerprintGenerator, MolFromSmiles
        from refnd.kernels.molecules import RealFingerprint, TanimotoReal
    
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(fpSize=1024, radius=2)
        mol = MolFromSmiles("c1ccccc1")
        fp = RealFingerprint(mfpgen.GetCountFingerprint(mol))
        print(fp.norm_sq(), len(fp))
    """
    def __new__(cls, fp: UIntSparseIntVect) -> RealFingerprint:
        r"""
        Construct from an RDKit ``UIntSparseIntVect`` (e.g. from ``GetCountFingerprint``).
        
        Raises ``TypeError`` if given a ``ULongSparseIntVect`` from
        ``GetSparseCountFingerprint``. That variant uses the full 64-bit hash space
        as its length, which cannot be stored as a dense vector. Use
        ``GetCountFingerprint`` instead, which folds indices modulo ``fpSize`` and
        returns a ``UIntSparseIntVect`` with a manageable length.
        """
    @staticmethod
    def from_list(values: typing.Sequence[builtins.float]) -> RealFingerprint:
        r"""
        Construct from a list of floats.
        """
    @staticmethod
    def from_np(arr: numpy.typing.NDArray[numpy.float32]) -> RealFingerprint:
        r"""
        Construct from a numpy float32 or float64 array.
        """
    def to_rdkit(self) -> UIntSparseIntVect:
        r"""
        Export as an RDKit ``UIntSparseIntVect``, compatible with ``GetCountFingerprint``.
        Only non-zero elements are stored; the length equals ``len(self)``.
        """
    def to_list(self) -> builtins.list[builtins.float]:
        r"""
        Export as a list of floats.
        """
    def to_np(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Export as a numpy float32 array.
        """
    def __len__(self) -> builtins.int: ...
    def norm_sq(self) -> builtins.float:
        r"""
        Squared Euclidean norm of the feature vector (``||x||²``).
        """

def largest_cluster(clusters: typing.Sequence[builtins.int]) -> tuple[builtins.int, builtins.int]:
    r"""
    Return the ID and size of the largest cluster.
    
    Convenience helper — iterates over a cluster-label vector and finds the
    most populous label.
    
    Args:
        clusters: A list of cluster IDs (e.g. from ``connected_components`` or
                  ``find_communities``).
    
    Returns:
        A tuple ``(cluster_id, size)`` for the largest cluster.
    """

def read_fasta(path: builtins.str) -> builtins.list[tuple[builtins.str, builtins.str]]:
    r"""
    Parse a FASTA file and return all records as a list of ``(header, sequence)`` pairs.
    
    The header string is the full description line without the leading ``>``.
    The sequence is the concatenation of all continuation lines for that record,
    with whitespace stripped.
    
    Args:
        path: Path to the FASTA file.
    
    Returns:
        A list of ``(header, sequence)`` tuples, one per FASTA record.
    
    Raises:
        IOError: If the file cannot be opened or is not valid UTF-8.
    
    Example::
    
        from refnd.utils import read_fasta
    
        records = read_fasta("proteins.fasta")
        header, seq = records[0]
        print(header)  # "sp|P12345|MYPR_HUMAN ..."
        print(seq)     # "MKTAYIAKQRQISFVKSHFSRQ..."
    """

