# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import enum
import typing
from . import molecules
from . import protein
__all__ = [
    "KernelVariant",
    "molecules",
    "protein",
]

@typing.final
class KernelVariant(enum.Enum):
    ProteinGlobal = ...
    ProteinLocal = ...
    TanimotoBit = ...
    TanimotoReal = ...

