# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import enum
import typing
from . import alignments
from . import molecules
__all__ = [
    "KernelVariant",
    "alignments",
    "molecules",
]

@typing.final
class KernelVariant(enum.Enum):
    AlignmentGlobal = ...
    AlignmentLocal = ...
    TanimotoBit = ...
    TanimotoReal = ...

